apiVersion: v1
kind: Namespace
metadata:
  name: cilium-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: cilium-test
data:
  default.conf: |
    server {
        listen       80;
        server_name  _;
        location / {
          proxy_pass http://db-server:3306/;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: cilium-test
spec:
  selector:
    app: api-server
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  namespace: cilium-test
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 4
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: config
      volumes:
        - name: config
          configMap:
            name: api-config