apiVersion: v1
kind: Namespace
metadata:
  name: cilium-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: cilium-test
data:
  default.conf: |
    server {
        listen       3306;
        server_name  _;
        location / {
          return 200 "db data";
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: db-server
  namespace: cilium-test
spec:
  selector:
    app: db-server
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-server-deployment
  namespace: cilium-test
spec:
  selector:
    matchLabels:
      app: db-server
  replicas: 2
  template:
    metadata:
      labels:
        app: db-server
    spec:
      containers:
        - name: db-server
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: config
      volumes:
        - name: config
          configMap:
            name: db-config