apiVersion: v1
kind: Namespace
metadata:
  name: cilium-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-config
  namespace: cilium-test
data:
  default.conf: |
    server {
        listen       80;
        server_name  _;
        location / {
          proxy_hide_header "Content-Type";
          proxy_pass http://api-server/;
          add_header Content-Type text/plain;
        }
        location /db/ {
          proxy_hide_header "Content-Type";
          proxy_pass http://db-server:3306/;
          add_header Content-Type text/plain;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  namespace: cilium-test
spec:
  type: NodePort
  selector:
    app: reverse-proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-deployment
  namespace: cilium-test
spec:
  selector:
    matchLabels:
      app: reverse-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: config
      volumes:
        - name: config
          configMap:
            name: reverse-proxy-config